name: Bruno Mentges de Carvalho
url: http://bmentges.github.io
description: My Blog on Software Development, Management and Personal Stuff
pygments: true
permalink: /:year/:month/:day/:title
safe: false
